steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/microservices-nats-nest/images-register-docker/payments-ms-prod",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker" # demonio de docker
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/microservices-nats-nest/images-register-docker/payments-ms-prod",
      ]
options:
  logging: CLOUD_LOGGING_ONLY